<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>csharp_wpf_conversor_moedas</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Assets\brasil.png" />
    <None Remove="Resources\Assets\converter.png" />
    <None Remove="Resources\Assets\estados-unidos.png" />
    <None Remove="Resources\Assets\japao.png" />
    <None Remove="Resources\Assets\reino-unido.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Assets\brasil.png" />
    <Resource Include="Resources\Assets\converter.png" />
    <Resource Include="Resources\Assets\estados-unidos.png" />
    <Resource Include="Resources\Assets\japao.png" />
    <Resource Include="Resources\Assets\reino-unido.png" />
  </ItemGroup>

</Project>
